export default {
    regions: ['EUN1', 'EUW1', 'BR1', 'JP1', 'KR', 'LA1', 'LA2', 'NA1', 'OC1', 'TR1', 'RU'],
    regionTranslates: {
        EUN1: 'EUNE',
        EUW1: 'EUW',
        BR1: 'BR',
        JP1: 'JP',
        KR: 'KR',
        LA1: 'LA1',
        LA2: 'LA2',
        NA1: 'NA',
        OC1: 'OC',
        TR1: 'TR',
        RU: 'RU',
    },
    languageTranslates: {
        cs_CZ: 'Czech (Czech Republic)',
        el_GR: 'Greek (Greece)',
        pl_PL: 'Polish (Poland)',
        ro_RO: 'Romanian (Romania)',
        hu_HU: 'Hungarian (Hungary)',
        en_GB: 'English (United Kingdom)',
        de_DE: 'German (Germany)',
        es_ES: 'Spanish (Spain)',
        it_IT: 'Italian (Italy)',
        fr_FR: 'French (France)',
        ja_JP: 'Japanese (Japan)',
        ko_KR: 'Korean (Korea)',
        es_MX: 'Spanish (Mexico)',
        es_AR: 'Spanish (Argentina)',
        pt_BR: 'Portuguese (Brazil)',
        en_US: 'English (United States)',
        en_AU: 'English (Australia)',
        ru_RU: 'Russian (Russia)',
        tr_TR: 'Turkish (Turkey)',
        ms_MY: 'Malay (Malaysia)',
        en_PH: 'English (Republic of the Philippines)',
        en_SG: 'English (Singapore)',
        th_TH: 'Thai (Thailand)',
        vn_VN: 'Vietnamese (Viet Nam)',
        id_ID: 'Indonesian (Indonesia)',
        zh_MY: 'Chinese (Malaysia)',
        zh_CN: 'Chinese (China)',
        zh_TW: 'Chinese (Taiwan)',
    },
    routes: {
        AMERICAS: ['NA', 'BR', 'LA1', 'LA2'],
        ASIA: ['KR', 'JP'],
        EUROPE: ['EUNE', 'EUW', 'TR', 'RU'],
        SEA: ['OC1'],
    },
    basicGamemodes: {
        'Blind pick': 2,
        'Draft pick': 400,
        'Solo/Duo': 4,
        Flex: 6,
        ARAM: 450,
    },
}
